/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilEmpty {
    'text': string;
  }
  interface StencilEmptyAttributes extends StencilHTMLAttributes {
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StencilEmpty': Components.StencilEmpty;
  }

  interface StencilIntrinsicElements {
    'stencil-empty': Components.StencilEmptyAttributes;
  }


  interface HTMLStencilEmptyElement extends Components.StencilEmpty, HTMLStencilElement {}
  var HTMLStencilEmptyElement: {
    prototype: HTMLStencilEmptyElement;
    new (): HTMLStencilEmptyElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-empty': HTMLStencilEmptyElement
  }

  interface ElementTagNameMap {
    'stencil-empty': HTMLStencilEmptyElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
